---

- name: install Linked Data API
  get_url: dest=/tmp/dna.war force=no  url=https://github.com/rob-metalinkage/dna_demodata/blob/master/dna.war?raw=true
#  unarchive: creates=/tmp/eclipse-rdf4j-2.1.1/war/rdf4j-server.war dest=/tmp  remote_src=yes src=http://www.eclipse.org/downloads/download.php?file=/rdf4j/eclipse-rdf4j-2.1.1-sdk.zip&r=1
  tags: [elda]

- name: copy war to tomcat
  # Will skip if file war installed
  command: cp /tmp/dna.war /var/lib/tomcat7/webapps/ creates=/var/lib/tomcat7/webapps/dna.war
  tags: elda
  
- name: clear bundled ELDA configs
  shell: rm -rf /var/lib/tomcat7/webapps/dna/lda-assets/resources/*
  tags: [elda, elda-config]

# this is kinda ugly 
- name: update ELDA configs
  shell: cp  -r {{ project_path }}/../django-skosxl/configs/* /var/lib/tomcat7/webapps/dna/lda-assets/resources
  tags: [elda, elda-config]
  
- name: set perms 
  file: path=/var/lib/tomcat7/webapps/dna/lda-assets/resources group=tomcat7 owner=tomcat7 mode=755 
  tags: [elda, elda-config]