---
- name: ensure known hosts
  shell: mkdir ~/.ssh; touch ~/.ssh/known_hosts
  become_user: '{{ application_user }}'
  tags: [config]

  
- name: remove github.com from known host
  shell: ssh-keygen -R github.com
  become_user: '{{ application_user }}'
  when: setup_git_repo is defined and setup_git_repo
  tags: [config]

- name: ensure github.com in known host
  shell: ssh-keyscan -H github.com > ~/.ssh/known_hosts
  become_user: '{{ application_user }}'
  when: setup_git_repo is defined and setup_git_repo
  tags: [config]

- name: check if virtualenv already exists
  stat: path={{venv}}
  register: venv_dir

- name: create virtualenv
  shell: virtualenv --system-site-packages {{venv}}
  become_user: '{{ application_user }}'
  when: venv_dir.stat.isdir is not defined

- name: pip install
  pip: virtualenv={{venv}} chdir={{ project_path }} requirements=requirements_gaz.txt
  become_user: '{{ application_user }}'
  tags: [update, debug]

- name: mv project local settings across synced file system if necessary
  command: mv /tmp/local_key.py {{ project_path }}/{{ project_name }}/settings/local_key.py
  become_user: '{{ application_user }}'
  notify: restart django
  tags: [settings]
 
- name: write project local settings - sync filesystem safe
  template: src=roles/gazetteer/files/local_settings_gaz.py.j2 dest=/tmp/local_settings_gaz.py
  become_user: '{{ application_user }}'
  tags: [settings]


- name: mv project local settings across synced file system if necessary
  command: mv /tmp/local_settings_gaz.py {{ project_path }}/{{ project_name }}/settings/local_settings_gaz.py
  become_user: '{{ application_user }}'
  notify: restart django
  tags: [settings]

- name: syncdb
  django_manage: command="syncdb --noinput" virtualenv={{ venv }} app_path={{ project_path }}
  become_user: '{{ application_user }}'
  tags: [update, syncdb]

- name: load initial data
  django_manage: app_path={{ project_path }} virtualenv={{ venv }} fixtures='{{ fixtures }}' command=loaddata
  become_user: '{{ application_user }}'
  tags: [settings, initial_data]

- name: restart nginx
  shell: 'sudo service nginx restart'

